
















































































































































































































































































































































































































































































































































































































































































































        return jsonify({'error': 'Error al obtener condominios'}), 500        print(f"❌ Error al obtener condominios: {e}")    except Exception as e:        return jsonify([condo.to_dict() for condo in condominiums])        condominiums = Condominium.query.all()    try:def get_condominiums():@main.route('/condominiums', methods=['GET'])        return jsonify({"error": f"Error creando unidad: {str(e)}"}), 500        db.session.rollback()    except Exception as e:                }), 201            }                "full_address": unidad.get_full_address()                "name": unidad.name,                "property_number": unidad.property_number,                "id": unidad.id,            "unidad": {            "message": "✅ Unidad creada exitosamente",        return jsonify({                db.session.commit()        db.session.add(unidad)                )            status='disponible'            created_by=current_user.id,            condominium_id=1,  # Por defecto            notes=data.get('notes', ''),            land_use=data.get('land_use'),            topography=data.get('topography'),            depth_meters=float(data['depth_meters']) if data.get('depth_meters') else None,            front_meters=float(data['front_meters']) if data.get('front_meters') else None,            parking_spaces=int(data['parking_spaces']) if data.get('parking_spaces') else None,            bathrooms=int(data['bathrooms']) if data.get('bathrooms') else None,            bedrooms=int(data['bedrooms']) if data.get('bedrooms') else None,            area_construction_m2=float(data['area_construction_m2']) if data.get('area_construction_m2') else None,            area_m2=float(data['area_m2']),            sector=data.get('sector'),            floor=data.get('floor'),            building=data.get('building'),            longitude=float(data['longitude']),            latitude=float(data['latitude']),            address_reference=data.get('address_reference', ''),            house_number=data.get('house_number', ''),            cross_street=data['cross_street'],            main_street=data['main_street'],            property_type=data['property_type'],            name=data['name'],            property_number=data['property_number'],        unidad = Unit(        # Crear unidad                    return jsonify({"error": f"El número de propiedad '{data['property_number']}' ya existe"}), 400        if Unit.query.filter_by(property_number=data['property_number']).first():        # Verificar si ya existe                        return jsonify({"error": f"Campo '{campo}' es obligatorio"}), 400            if not data.get(campo):        for campo in campos_obligatorios:        campos_obligatorios = ['property_number', 'name', 'property_type', 'main_street', 'cross_street', 'latitude', 'longitude', 'area_m2']        # Validar campos obligatorios                data = request.get_json()                    return jsonify({"error": "Acceso denegado"}), 403        if current_user.role != 'MASTER':        current_user = get_jwt_identity()    try:    """Crear unidad individualmente"""def crear_unidad_individual():@jwt_required()@main.route('/api/master/crear-unidad', methods=['POST'])            return jsonify({"error": f"Error procesando archivo: {str(e)}"}), 500        db.session.rollback()    except Exception as e:                })            "unidades_procesadas": unidades_procesadas            "message": f"✅ {len(unidades_procesadas)} unidades cargadas exitosamente",        return jsonify({                db.session.commit()        # Si no hay errores, guardar todo                    }), 400                "unidades_procesadas": 0                "detalles": errores,                "error": "Errores en el archivo CSV",            return jsonify({            db.session.rollback()        if errores:                        errores.append(f"Fila {row_num}: Error procesando - {str(e)}")            except Exception as e:                errores.append(f"Fila {row_num}: Error en formato de número - {str(e)}")            except ValueError as e:                                unidades_procesadas.append(row['property_number'])                db.session.add(unidad)                                )                    status='disponible'                    created_by=current_user.id,                    condominium_id=1,  # Por defecto, luego se puede configurar                    notes=row.get('notes', ''),                    land_use=row.get('land_use'),                    topography=row.get('topography'),                    depth_meters=float(row['depth_meters']) if row.get('depth_meters') else None,                    front_meters=float(row['front_meters']) if row.get('front_meters') else None,                    parking_spaces=int(row['parking_spaces']) if row.get('parking_spaces') else None,                    bathrooms=int(row['bathrooms']) if row.get('bathrooms') else None,                    bedrooms=int(row['bedrooms']) if row.get('bedrooms') else None,                    area_construction_m2=float(row['area_construction_m2']) if row.get('area_construction_m2') else None,                    area_m2=float(row['area_m2']),                    sector=row.get('sector'),                    floor=row.get('floor'),                    building=row.get('building'),                    longitude=float(row['longitude']),                    latitude=float(row['latitude']),                    address_reference=row.get('address_reference', ''),                    house_number=row.get('house_number', ''),                    cross_street=row['cross_street'],                    main_street=row['main_street'],                    property_type=row['property_type'],                    name=row['name'],                    property_number=row['property_number'],                unidad = Unit(                # Crear unidad                                    continue                    errores.append(f"Fila {row_num}: Número de propiedad '{row['property_number']}' ya existe")                if Unit.query.filter_by(property_number=row['property_number']).first():                # Verificar si ya existe                                        continue                        errores.append(f"Fila {row_num}: Campo '{campo}' es obligatorio")                    if not row.get(campo):                for campo in campos_obligatorios:                campos_obligatorios = ['property_number', 'name', 'property_type', 'main_street', 'cross_street', 'latitude', 'longitude', 'area_m2']                # Validar campos obligatorios            try:        for row_num, row in enumerate(csv_reader, start=2):  # row_num incluye encabezado                errores = []        unidades_procesadas = []                csv_reader = csv.DictReader(stream)        stream = io.StringIO(csv_file.stream.read().decode("UTF8"), newline=None)                import io        import csv        # Leer y procesar CSV                    return jsonify({"error": "El archivo debe ser CSV"}), 400        if not csv_file.filename.endswith('.csv'):                    return jsonify({"error": "Nombre de archivo vacío"}), 400        if csv_file.filename == '':        csv_file = request.files['csv_file']                    return jsonify({"error": "No se envió archivo CSV"}), 400        if 'csv_file' not in request.files:                    return jsonify({"error": "Acceso denegado"}), 403        if current_user.role != 'MASTER':        current_user = get_jwt_identity()    try:    """Cargar unidades masivamente desde CSV"""def cargar_unidades_csv():@jwt_required()@main.route('/api/master/cargar-unidades-csv', methods=['POST'])            return jsonify({"error": f"Error generando plantilla: {str(e)}"}), 500    except Exception as e:                )            headers={"Content-Disposition": "attachment;filename=plantilla_unidades.csv"}            mimetype="text/csv",            output.getvalue(),        return Response(                output.seek(0)        from flask import Response        # Devolver archivo                    writer.writerow(example)        for example in examples:                ]             '-0.180750', '-78.467950', '', '', 'Loteamiento Norte', '350.0', '', '', '', '', '15.0', '23.3', 'plano', 'residencial', '']            ['T-A5', 'Terreno A5', 'terreno', 'Av. Principal', 'Calle Segunda', 'S/N', 'Esquina noroeste',             '-0.180700', '-78.467900', '', '', 'Manzana B', '120.0', '95.0', '3', '2', '2', '', '', '', '', ''],            ['C-25', 'Casa 25', 'casa', 'Av. Las Palmeras', 'Calle Los Pinos', '25-A', 'Frente al parque',             '-0.180653', '-78.467834', 'Torre A', '1', 'Zona Residencial', '85.5', '75.0', '2', '2', '1', '', '', '', '', ''],            ['A-101', 'Apartamento 101', 'apartamento', 'Av. Principal', 'Calle Segunda', '101', 'Frente al ascensor',         examples = [        # Ejemplos de datos                writer.writerow(headers)                ]            'notes'              # Observaciones adicionales            'land_use',          # "residencial", "comercial" (solo terrenos)            'topography',        # "plano", "inclinado" (solo terrenos)            'depth_meters',      # "23.3" (solo terrenos)            'front_meters',      # "15.0" (solo terrenos)            'parking_spaces',    # "1", "2" (para apartamentos/casas)            'bathrooms',         # "2", "1" (para apartamentos/casas)            'bedrooms',          # "2", "3" (para apartamentos/casas)            'area_construction_m2', # "75.0", "180.0" (para construcciones)            'area_m2',           # "85.5", "350.0" (OBLIGATORIO)            'sector',            # "Zona Residencial", "Área Comercial"            'floor',             # "1", "PB", "Sótano 2"             'building',          # "Torre A", "Edificio Principal"            'longitude',         # "-78.467834" (OBLIGATORIO)            'latitude',          # "-0.180653" (OBLIGATORIO)            'address_reference', # "Frente al parque", "Entre calles"            'house_number',      # "S/N", "25-A", "102"            'cross_street',      # "Calle Segunda" (OBLIGATORIO)            'main_street',       # "Av. Principal" (OBLIGATORIO)            'property_type',     # "apartamento", "casa", "local_comercial", "parqueadero", "bodega", "galpon", "terreno" (OBLIGATORIO)            'name',              # "Apartamento 101", "Casa 25" (OBLIGATORIO)            'property_number',    # Ej: "A-101", "C-25", "BOD-12" (OBLIGATORIO)        headers = [        # Encabezados según el modelo                writer = csv.writer(output)        output = io.StringIO()                import io        import csv        # Crear CSV en memoria                    return jsonify({"error": "Acceso denegado"}), 403        if current_user.role != 'MASTER':        current_user = get_jwt_identity()    try:    """Descargar plantilla CSV para carga masiva de unidades"""def descargar_plantilla_unidades():@jwt_required()@main.route('/master/descargar-plantilla-unidades')                return jsonify({"error": f"Error obteniendo estadísticas: {str(e)}"}), 500    except Exception as e:                })            "condominios_recientes": []            "condominios_pendientes": 0,            "condominios_activos": 0,            "total_usuarios": User.query.count(),            "total_condominios": 0,        return jsonify({        # Por ahora devolvemos datos de ejemplo        # Aquí irá la lógica para obtener estadísticas                    return jsonify({"error": "Acceso denegado"}), 403        if current_user.role != 'MASTER':                current_user = get_jwt_identity()    try:    """Estadísticas globales del sistema para MASTER"""def api_master_estadisticas():@jwt_required()@main.route('/api/master/estadisticas')        return jsonify({"error": f"Error accediendo al panel maestro: {str(e)}"}), 500    except Exception as e:                return render_template('master/panel.html', config=config)                config = current_app.get_tenant_config(tenant)        tenant = get_tenant()        from app.tenant import get_tenant                    return jsonify({"error": "Acceso denegado. Se requiere rol MASTER"}), 403        if current_user.role != 'MASTER':                current_user = get_jwt_identity()    try:    """Panel exclusivo para usuarios MASTER"""def master_panel():@jwt_required()@main.route('/master')# =============================================================================# RUTAS MAESTRO    # =============================================================================                             config=config)                         mensaje="📊 Reportes - Próximamente",    return render_template('services/reportes.html',    config = current_app.get_tenant_config(tenant)    tenant = get_tenant()    from app.tenant import get_tenant    """Reportes del sistema (próximamente)"""def reportes():@main.route('/reportes')                         config=config)                         mensaje="💳 Sistema de Pagos - Próximamente",    return render_template('services/pagos.html',    config = current_app.get_tenant_config(tenant)    tenant = get_tenant()    from app.tenant import get_tenant    """Sistema de pagos (próximamente)"""def pagos():@main.route('/pagos')                         config=config)                         mensaje="🏢 Gestión de Unidades - Próximamente",    return render_template('services/unidades.html',    config = current_app.get_tenant_config(tenant)    tenant = get_tenant()    from app.tenant import get_tenant    """Gestión de unidades (próximamente)"""def unidades():@main.route('/unidades')# ✅ RUTAS DE SERVICIOS FUTUROS    return "OK", 200    """Health check para monitoreo"""def health():@main.route('/health')        return f"Error listando usuarios: {str(e)}"    except Exception as e:                             config=config)                             users=users,        return render_template('admin/usuarios.html',        users = User.query.all()                config = current_app.get_tenant_config(tenant)        tenant = get_tenant()        from app.tenant import get_tenant    try:    """Listar todos los usuarios (solo admin)"""def listar_usuarios():@main.route('/usuarios')                         config=config)                         mensaje="🏠 Panel de usuario - Próximamente",    return render_template('user/dashboard.html',     config = current_app.get_tenant_config(tenant)    tenant = get_tenant()    from app.tenant import get_tenant    """Dashboard para usuarios aprobados"""def dashboard():@main.route('/dashboard')        return redirect('/admin')    except Exception as e:        return redirect('/admin')            db.session.commit()            user.status = 'rejected'         if user:        user = User.query.get(user_id)    try:    """Rechazar usuario pendiente"""def rechazar_usuario(user_id):@main.route('/rechazar/<int:user_id>')        return redirect('/admin')    except Exception as e:        return redirect('/admin')            db.session.commit()            user.status = 'active'        if user:        user = User.query.get(user_id)    try:    """Aprobar usuario pendiente"""def aprobar_usuario(user_id):@main.route('/aprobar/<int:user_id>')                             config=config)                             error=f"Error cargando panel: {str(e)}",        return render_template('admin/panel.html',        config = current_app.get_tenant_config(tenant)        tenant = get_tenant()        from app.tenant import get_tenant    except Exception as e:                                 config=config)                             rejected_count=len(rejected_users),                             active_count=len(active_users),                             pending_users=pending_users,        return render_template('admin/panel.html',                 rejected_users = User.query.filter_by(status='rejected').all()        active_users = User.query.filter_by(status='active').all()        pending_users = User.query.filter_by(status='pending').all()        # Listar usuarios pendientes de aprobación                config = current_app.get_tenant_config(tenant)        tenant = get_tenant()        from app.tenant import get_tenant        # Obtener configuración    try:    """Panel de administración para aprobar usuarios"""def admin_panel():@main.route('/admin')                             config=config)                             error=f"❌ Error en login: {str(e)}",        return render_template('auth/login.html',         config = current_app.get_tenant_config(tenant)        tenant = get_tenant()        from app.tenant import get_tenant    except Exception as e:            return render_template('auth/login.html', config=config)                                            config=config)                                    error="❌ Credenciales incorrectas",                return render_template('auth/login.html',            else:                                    config=config)                                    mensaje=f"🎉 Bienvenido {user.name}!",                return render_template('auth/login.html',                                                         config=config)                                        error="❌ Tu cuenta fue rechazada. Contacta al administrador",                    return render_template('auth/login.html',                elif user.status == 'rejected':                                        config=config)                                        error="⏳ Tu cuenta está pendiente de aprobación",                    return render_template('auth/login.html',                if user.status == 'pending':            if user:                        user = User.query.filter_by(email=email, password_hash=pwd_hash).first()                        pwd_hash = hashlib.sha256(password.encode()).hexdigest()            password = request.form['password']            email = request.form['email']        if request.method == 'POST':                config = current_app.get_tenant_config(tenant)        tenant = get_tenant()        from app.tenant import get_tenant        # Obtener configuración    try:    """Login de usuarios"""def login():@main.route('/login', methods=['GET', 'POST'])                             config=config)                             error=f"❌ Error en registro: {str(e)}",        return render_template('auth/registro.html',         config = current_app.get_tenant_config(tenant)        tenant = get_tenant()        from app.tenant import get_tenant    except Exception as e:            return render_template('auth/registro.html', config=config)        config = current_app.get_tenant_config(tenant)        tenant = get_tenant()        from app.tenant import get_tenant        # GET request - obtener configuración                                        config=config)                                mensaje=f"✅ Registrado exitosamente. Tu email {email} está pendiente de aprobación en {tenant}.",            return render_template('auth/registro.html',                         db.session.commit()            db.session.add(user)                        )                status='pending'                tenant=tenant,                password_hash=pwd_hash,                 country=request.form['country'],  # ✅ NUEVO                city=request.form['city'],        # ✅ NUEVO                phone=request.form['phone'],      # ✅ NUEVO                name=name,                 email=email,             user = User(                                                config=config)                                    error="❌ Este email ya está registrado",                return render_template('auth/registro.html',             if existing_user:            existing_user = User.query.filter_by(email=email).first()            # Verificar si el usuario ya existe                        config = current_app.get_tenant_config(tenant)            # Obtener configuración para el template                        tenant = get_tenant()            from app.tenant import get_tenant            # USAR TENANT DINÁMICO                        pwd_hash = hashlib.sha256(password.encode()).hexdigest()            password = request.form['password']            name = request.form['name']            email = request.form['email']        if request.method == 'POST':    try:    """Registro de nuevos usuarios"""def registro():@main.route('/registro', methods=['GET', 'POST'])    return render_template('home.html', config=config)    config = current_app.get_tenant_config(tenant)    tenant = get_tenant()    from app.tenant import get_tenantdef home():@main.route('/')# =============================================================================# RUTAS EXISTENTES (TUS RUTAS ORIGINALES)# =============================================================================    })        "user": current_user.email        "message": "Bienvenido administrador",    return jsonify({            return jsonify({"error": "Acceso denegado. Se requiere rol de administrador"}), 403    if current_user.role not in ['ADMIN', 'MASTER']:        current_user = get_jwt_identity()    """Ruta solo para administradores"""def api_admin_only():@jwt_required()@main.route('/api/auth/admin-only', methods=['GET'])    })        "user_role": current_user.role        "message": f"Acceso concedido para {current_user.email}",    return jsonify({    current_user = get_jwt_identity()    """Ruta protegida de ejemplo"""def api_protected():@jwt_required()@main.route('/api/auth/protected', methods=['GET'])        return jsonify({"error": f"Error obteniendo usuario: {str(e)}"}), 500    except Exception as e:                })            }                "status": current_user.status                "role": current_user.role,                "email": current_user.email,                "name": current_user.name,                "id": current_user.id,            "user": {        return jsonify({                current_user = get_jwt_identity()    try:    """Obtener información del usuario actual"""def api_get_me():@jwt_required()@main.route('/api/auth/me', methods=['GET'])        return jsonify({"error": f"Error en login: {str(e)}"}), 500    except Exception as e:                })            "access_token": access_token            },                "role": user.role                "email": user.email,                "name": user.name,                "id": user.id,            "user": {            "message": "Login exitoso",        return jsonify({                )            expires_delta=timedelta(days=30)            identity=user,        access_token = create_access_token(        # Crear token JWT                    return jsonify({"error": "Cuenta pendiente de aprobación"}), 403        if user.status != 'active':                    return jsonify({"error": "Credenciales incorrectas"}), 401        if not user:                user = User.query.filter_by(email=email, password_hash=pwd_hash).first()        # Buscar usuario                pwd_hash = hashlib.sha256(password.encode()).hexdigest()        password = data['password']        email = data['email']                    return jsonify({"error": "Email y contraseña requeridos"}), 400        if not data or not data.get('email') or not data.get('password'):                data = request.get_json()    try:    """Login de usuario con JWT"""def api_login():@main.route('/api/auth/login', methods=['POST'])        return jsonify({"error": f"Error en registro: {str(e)}"}), 500        db.session.rollback()    except Exception as e:                }), 201            "access_token": access_token            },                "role": user.role                "country": user.country, # ✅ NUEVO                "city": user.city,      # ✅ NUEVO                "phone": user.phone,    # ✅ NUEVO                "email": user.email,                "name": user.name,                "id": user.id,            "user": {            "message": "Usuario registrado exitosamente",        return jsonify({                )            expires_delta=timedelta(days=30)            identity=user,        access_token = create_access_token(        # Crear token JWT                db.session.commit()        db.session.add(user)                )            status='active'            role='USER',            tenant=tenant,            password_hash=pwd_hash,            country=data.get('country', ''),  # ✅ NUEVO            city=data.get('city', ''),        # ✅ NUEVO            phone=data.get('phone', ''),      # ✅ NUEVO            name=name,            email=email,        user = User(        # Crear usuario                tenant = get_tenant()        from app.tenant import get_tenant        # Obtener tenant                pwd_hash = hashlib.sha256(password.encode()).hexdigest()        # Hash de contraseña                    return jsonify({"error": "Este email ya está registrado"}), 400        if existing_user:        existing_user = User.query.filter_by(email=email).first()        # Verificar si el usuario ya existe                password = data['password']        name = data.get('name', '')        email = data['email']                    return jsonify({"error": "Email y contraseña requeridos"}), 400        if not data or not data.get('email') or not data.get('password'):                data = request.get_json()    try:    """Registro de usuario con JWT"""def api_register():@main.route('/api/auth/register', methods=['POST'])# =============================================================================# AUTENTICACIÓN JWT - NUEVOS ENDPOINTS# =============================================================================    })        "message": "Backend Flask activo en Railway"        "timestamp": datetime.utcnow().isoformat(),        "status": "✅ API funcionando correctamente",     return jsonify({def test_api():@main.route('/api/test')main = Blueprint('main', __name__)from datetime import datetime, timedeltaimport tracebackimport hashlibfrom app.models import User, Condominium, Unit  # Asegúrate de importar los modelos correctamentefrom app import dbfrom flask_jwt_extended import create_access_token, jwt_required, get_jwt_identityfrom flask import Blueprint, request, render_template, redirect, url_for, current_app, jsonify