# c:\condomanager-saas\migrations\versions\001_initial_migration.py
"""Initial migration with all tables.

Revision ID: 001
Revises: 
Create Date: 2025-11-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('city', sa.String(length=50), nullable=True),
        sa.Column('country', sa.String(length=50), nullable=True),
        sa.Column('password_hash', sa.String(length=255), nullable=True),
        sa.Column('tenant', sa.String(length=50), nullable=True),
        sa.Column('role', sa.String(length=20), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        # La columna unit_id se crea aquí directamente, pero sin la FK todavía
        sa.Column('unit_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_table('condominiums',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('legal_name', sa.String(length=200), nullable=True),
        sa.Column('ruc', sa.String(length=20), nullable=True),
        sa.Column('main_street', sa.String(length=100), nullable=False),
        sa.Column('cross_street', sa.String(length=100), nullable=False),
        sa.Column('house_number', sa.String(length=20), nullable=True),
        sa.Column('city', sa.String(length=50), nullable=False),
        sa.Column('country', sa.String(length=50), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('subdomain', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=30), nullable=True),
        sa.Column('billing_day', sa.Integer(), nullable=True),
        sa.Column('grace_days', sa.Integer(), nullable=True),
        sa.Column('trial_start_date', sa.Date(), nullable=True),
        sa.Column('trial_end_date', sa.Date(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('admin_user_id', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('ruc'),
        sa.UniqueConstraint('subdomain')
    )
    op.create_table('units',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('property_number', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('property_type', sa.String(length=50), nullable=True),
        sa.Column('main_street', sa.String(length=200), nullable=True),
        sa.Column('cross_street', sa.String(length=200), nullable=True),
        sa.Column('house_number', sa.String(length=20), nullable=True),
        sa.Column('address_reference', sa.Text(), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('building', sa.String(length=50), nullable=True),
        sa.Column('floor', sa.String(length=20), nullable=True),
        sa.Column('sector', sa.String(length=50), nullable=True),
        sa.Column('area_m2', sa.Float(), nullable=True),
        sa.Column('area_construction_m2', sa.Float(), nullable=True),
        sa.Column('bedrooms', sa.Integer(), nullable=True),
        sa.Column('bathrooms', sa.Integer(), nullable=True),
        sa.Column('parking_spaces', sa.Integer(), nullable=True),
        sa.Column('front_meters', sa.Float(), nullable=True),
        sa.Column('depth_meters', sa.Float(), nullable=True),
        sa.Column('topography', sa.String(length=50), nullable=True),
        sa.Column('land_use', sa.String(length=100), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('condominium_id', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['condominium_id'], ['condominiums.id'], ),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # Ahora que la tabla 'units' existe, podemos añadir la Foreign Key en 'users'
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_users_unit_id_units', 'units', ['unit_id'], ['id'])

    op.create_table('condominium_configs',
        sa.Column('tenant', sa.String(length=50), nullable=False),
        sa.Column('primary_color', sa.String(length=7), nullable=True),
        sa.Column('logo_url', sa.String(length=255), nullable=True),
        sa.Column('commercial_name', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('tenant')
    )
    op.create_table('invoices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('condominium_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('due_date', sa.Date(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['condominium_id'], ['condominiums.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_special_roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('condominium_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('assigned_by', sa.Integer(), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['condominium_id'], ['condominiums.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_special_roles')
    op.drop_table('invoices')
    op.drop_table('condominium_configs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_unit_id_units', type_='foreignkey')
    op.drop_table('units')
    op.drop_table('condominiums')
    op.drop_table('users')
    # ### end Alembic commands ###
