"""Add CondominiumModule and update Module for customization

Revision ID: 396bbea0d11c
Revises: 5dca09364acb
Create Date: 2025-11-24 16:39:01.674822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396bbea0d11c'
down_revision = '5dca09364acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create condominium_modules table
    op.create_table('condominium_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominium_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('price_override', sa.Float(), nullable=True),
    sa.Column('pricing_type', sa.String(length=20), nullable=True),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['condominium_id'], ['condominiums.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 2. Add new columns to modules table
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricing_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('maintenance_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('maintenance_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('maintenance_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('maintenance_message', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_column('maintenance_message')
        batch_op.drop_column('maintenance_end')
        batch_op.drop_column('maintenance_start')
        batch_op.drop_column('maintenance_mode')
        batch_op.drop_column('pricing_type')

    op.drop_table('condominium_modules')
    # ### end Alembic commands ###
