"""Add electronic signature fields to User

Revision ID: 4cf898c6dce8
Revises: 5cf5f83904bb
Create Date: 2025-11-23 01:14:27.793858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf898c6dce8'
down_revision = '5cf5f83904bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pdf_unsigned_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_signed_path', sa.String(length=500), nullable=True),
    sa.Column('signature_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requires_signature', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('condominium_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('collect_signatures_from_residents', sa.Boolean(), nullable=True),
    sa.Column('public_signature_link', sa.String(length=100), nullable=True),
    sa.Column('signature_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condominium_id'], ['condominiums.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_signature_link')
    )
    op.create_table('document_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('signature_type', sa.String(length=20), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resident_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('condominiums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('has_documents_module', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('has_billing_module', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('has_requests_module', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('legal_representative_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_condominium_legal_rep', 'users', ['legal_representative_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_electronic_signature', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('signature_certificate', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('signature_cert_password_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('signature_cert_password_hash')
        batch_op.drop_column('signature_certificate')
        batch_op.drop_column('has_electronic_signature')

    with op.batch_alter_table('condominiums', schema=None) as batch_op:
        batch_op.drop_constraint('fk_condominium_legal_rep', type_='foreignkey')
        batch_op.drop_column('legal_representative_id')
        batch_op.drop_column('has_requests_module')
        batch_op.drop_column('has_billing_module')
        batch_op.drop_column('has_documents_module')
        batch_op.drop_column('email')

    op.drop_table('resident_signatures')
    op.drop_table('document_signatures')
    op.drop_table('documents')
    # ### end Alembic commands ###
