"""Add TikTok profile to User

Revision ID: 5dca09364acb
Revises: 8791e2db074f
Create Date: 2025-11-23 20:10:59.287606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dca09364acb'
down_revision = '8791e2db074f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiktok_profile', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('tiktok_profile')

    # ### end Alembic commands ###
