"""Add whatsapp_provider and whatsapp_config to Condominium

Revision ID: 612c1bd9ab44
Revises: da39c0d286b8
Create Date: 2025-11-23 15:43:05.901989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612c1bd9ab44'
down_revision = 'da39c0d286b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominiums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominiums', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_config')
        batch_op.drop_column('whatsapp_provider')

    # ### end Alembic commands ###
