"""Add email and legal representative to Condominium

Revision ID: 66cff12c9df0
Revises: 5cf5f83904bb
Create Date: 2025-11-21 07:54:27.475683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cff12c9df0'
down_revision = '5cf5f83904bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominiums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('legal_representative_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['legal_representative_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominiums', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('legal_representative_id')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
