"""Add payment_config to Condominium

Revision ID: 7fcdeef25284
Revises: 5001610a08bf
Create Date: 2025-11-23 16:27:23.453099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcdeef25284'
down_revision = '5001610a08bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominiums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominiums', schema=None) as batch_op:
        batch_op.drop_column('payment_config')
        batch_op.drop_column('payment_provider')

    # ### end Alembic commands ###
