"""Add billing_contact_id to Condominium

Revision ID: 8010d399c59f
Revises: 396bbea0d11c
Create Date: 2025-11-24 20:45:12.591425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8010d399c59f'
down_revision = '396bbea0d11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # SOLO agregamos la nueva columna
    with op.batch_alter_table('condominiums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_contact_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_condominium_billing_contact', 'users', ['billing_contact_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominiums', schema=None) as batch_op:
        batch_op.drop_constraint('fk_condominium_billing_contact', type_='foreignkey')
        batch_op.drop_column('billing_contact_id')
    # ### end Alembic commands ###
