"""Initial migration with all current models

Revision ID: 81ce0dfd395b
Revises: 
Create Date: 2025-11-23 01:34:05.751316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ce0dfd395b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condominium_configs',
    sa.Column('tenant', sa.String(length=50), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('commercial_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tenant')
    )
    op.create_table('condominiums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ruc', sa.String(length=20), nullable=True),
    sa.Column('main_street', sa.String(length=100), nullable=False),
    sa.Column('cross_street', sa.String(length=100), nullable=False),
    sa.Column('house_number', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('subdomain', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('billing_day', sa.Integer(), nullable=True),
    sa.Column('grace_days', sa.Integer(), nullable=True),
    sa.Column('trial_start_date', sa.Date(), nullable=True),
    sa.Column('trial_end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('has_documents_module', sa.Boolean(), nullable=False),
    sa.Column('has_billing_module', sa.Boolean(), nullable=False),
    sa.Column('has_requests_module', sa.Boolean(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('legal_representative_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name='fk_condominium_admin_user'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_condominium_creator'),
    sa.ForeignKeyConstraint(['legal_representative_id'], ['users.id'], name='fk_condominium_legal_rep'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc'),
    sa.UniqueConstraint('subdomain')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_tax_code', sa.String(length=100), nullable=True),
    sa.Column('property_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('main_street', sa.String(length=200), nullable=True),
    sa.Column('cross_street', sa.String(length=200), nullable=True),
    sa.Column('house_number', sa.String(length=20), nullable=True),
    sa.Column('address_reference', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('building', sa.String(length=50), nullable=True),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('area_construction_m2', sa.Float(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('front_meters', sa.Float(), nullable=True),
    sa.Column('depth_meters', sa.Float(), nullable=True),
    sa.Column('topography', sa.String(length=50), nullable=True),
    sa.Column('land_use', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('condominium_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['condominium_id'], ['condominiums.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_tax_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('cellphone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('tenant', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('has_electronic_signature', sa.Boolean(), nullable=True),
    sa.Column('signature_certificate', sa.LargeBinary(), nullable=True),
    sa.Column('signature_cert_password_hash', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pdf_unsigned_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_signed_path', sa.String(length=500), nullable=True),
    sa.Column('signature_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requires_signature', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('condominium_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('collect_signatures_from_residents', sa.Boolean(), nullable=True),
    sa.Column('public_signature_link', sa.String(length=100), nullable=True),
    sa.Column('signature_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condominium_id'], ['condominiums.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_signature_link')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominium_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['condominium_id'], ['condominiums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_special_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('condominium_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['condominium_id'], ['condominiums.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('signature_type', sa.String(length=20), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resident_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resident_signatures')
    op.drop_table('document_signatures')
    op.drop_table('user_special_roles')
    op.drop_table('invoices')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_table('units')
    op.drop_table('condominiums')
    op.drop_table('condominium_configs')
    # ### end Alembic commands ###
