"""Add social media fields to User

Revision ID: 8791e2db074f
Revises: d393d46eb45b
Create Date: 2025-11-23 20:05:58.477785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8791e2db074f'
down_revision = 'd393d46eb45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitter_profile', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('facebook_profile', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_profile', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin_profile', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('linkedin_profile')
        batch_op.drop_column('instagram_profile')
        batch_op.drop_column('facebook_profile')
        batch_op.drop_column('twitter_profile')

    # ### end Alembic commands ###
