"""add environment and is_demo columns to condominium

Revision ID: 8847a3d1cb9a
Revises: f29657d51c73
Create Date: 2025-11-25 19:38:23.971381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8847a3d1cb9a'
down_revision = 'f29657d51c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominiums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('environment', sa.String(length=20), server_default='production', nullable=False))
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominiums', schema=None) as batch_op:
        batch_op.drop_column('is_demo')
        batch_op.drop_column('environment')

    # ### end Alembic commands ###
