"""add google drive fields to condominium

Revision ID: 93d2d799e37c
Revises: c5aa1aa1a28c
Create Date: 2025-11-25 19:12:06.184068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d2d799e37c'
down_revision = 'c5aa1aa1a28c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominiums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_root_folder_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('drive_folders_map', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('drive_refresh_token', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('drive_email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominiums', schema=None) as batch_op:
        batch_op.drop_column('drive_email')
        batch_op.drop_column('drive_refresh_token')
        batch_op.drop_column('drive_folders_map')
        batch_op.drop_column('drive_root_folder_id')

    # ### end Alembic commands ###
