"""Add manual payment fields

Revision ID: 9ed1eb3fddab
Revises: 7fcdeef25284
Create Date: 2025-11-23 18:15:17.155396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed1eb3fddab'
down_revision = '7fcdeef25284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('proof_of_payment', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_payments_reviewed_by', 'users', ['reviewed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_reviewed_by', type_='foreignkey')
        batch_op.drop_column('review_notes')
        batch_op.drop_column('review_date')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('proof_of_payment')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
