"""Add PlatformBankAccount model

Revision ID: a94a71d2bcc0
Revises: 3f4e3d49af73
Create Date: 2025-11-25 01:22:17.377454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94a71d2bcc0'
down_revision = '3f4e3d49af73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('account_holder', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=True),
    sa.Column('account_email', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_bank_accounts')
    # ### end Alembic commands ###
