"""Add condominium_id to User and enforce TenantQuery

Revision ID: bf6bfbac732c
Revises: 8847a3d1cb9a
Create Date: 2025-11-26 00:47:27.727028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6bfbac732c'
down_revision = '8847a3d1cb9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condominium_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_condominium_id', 'condominiums', ['condominium_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_condominium_id', type_='foreignkey')
        batch_op.drop_column('condominium_id')

    # ### end Alembic commands ###
